django-blog/accounts/urls.py
from django.urls import path

from .views import SignUpView

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

django-blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
]

django-blog/main/urls.py
from django.urls import path

from .views import HomePageView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'main'

urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/new/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
]

django-blog/accounts/models.py
from django.db import models

# Create your models here.

django-blog/main/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone


def get_deleted_user():
    return get_user_model().objects.get_or_create(username='deleted')[0]


class BlogPost(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    publication_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.SET(get_deleted_user),
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:post_detail', kwargs={'pk': self.pk})

django-blog/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

django-blog/main/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import BlogPost


class HomePageView(ListView):
    def get_queryset(self):
        return BlogPost.objects.order_by('-publication_date')


class PostDetailView(DetailView):
    model = BlogPost


class PostCreateView(CreateView):
    model = BlogPost
    fields = ['title', 'author', 'publication_date', 'body']
    template_name = 'main/blogpost_create_form.html'


class PostUpdateView(UpdateView):
    model = BlogPost
    fields = ['title', 'body']
    template_name = 'main/blogpost_update_form.html'


class PostDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('main:homepage')

django-blog/main/templates/main/base.html
{% load static %}
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="stylesheet">
    <link href="{% static 'main/style.css' %}" rel="stylesheet">

    <title>My Blog</title>
</head>
<body>
<header>
    <div class="nav-left">
        <h1><a href="{% url 'main:homepage' %}">My Blog</a></h1>
    </div>
    <div class="nav-right">
        <h1>
            {% if user.is_authenticated %}
                Hi, {{ user.username }}! | <a href="{% url 'logout' %}">Log Out</a>
            {% else %}
                <a href="{% url 'login' %}">Log In</a> | <a href="{% url 'accounts:signup' %}">Sign Up</a>
            {% endif %}
        </h1>
    </div>
</header>
<div>
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

django-blog/main/templates/main/blogpost_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="item">
        <h2>Delete Post</h2>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete the post "{{ blogpost.title }}"?</p>
            <input type="submit" value="Yes, delete it">
        </form>
    </div>
{% endblock content %}

django-blog/main/templates/main/blogpost_create_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="item">
        <h2>New Post</h2>
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    </div>
{% endblock content %}

django-blog/main/templates/main/blogpost_detail.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="item">
        <h1>{{ blogpost.title|escape }}</h1>
        <h3>By: {{ blogpost.author|escape }}</h3>
        <h3>Published: {{ blogpost.publication_date }}</h3>
        <div>{{ blogpost.body|escape|linebreaks }}</div>
        <hr>

        {% if user.is_authenticated %}
            <a href="{% url 'main:post_update' blogpost.pk %}"><button>Edit Post</button></a>
            <a href="{% url 'main:post_delete' blogpost.pk %}"><button>Delete Post</button></a>
        {% else %}
            To create, edit, and delete posts, please sign up and log in.
        {% endif %}
    </div>
{% endblock content %}

django-blog/main/templates/main/blogpost_list.html
{% extends 'main/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <a href="{% url 'main:post_create'%}">
            <div class="item">
                <h3>Create New Post</h3>
            </div>
        </a>
    {% endif %}

    {% for post in blogpost_list %}
        <a href="{% url 'main:post_detail' post.pk %}">
            <div class="item">
                <h3>{{ post.title|escape }}</h3>
                {{ post.body|truncatewords:50|escape|linebreaks }}
            </div>
        </a>
    {% endfor %}
{% endblock content %}

django-blog/main/templates/main/blogpost_update_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="item">
        <h2>Edit Post</h2>
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
    </div>
{% endblock content %}